[package]
name = "await-modify-do"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.0"
devicons = "0.6.11"
notify = "7.0.0"
ratatui = { version = "0.28.0", features = ["all-widgets"]}
tempfile = "3.14.0"
which = "7.0.0"
